### ISSUE TITLE
Support staged-recipes path format

### ISSUE THREAD

**Issue by cisaacstern** [yuvipanda/pangeo-forge-runner#10]
https://github.com/pangeo-forge/staged-recipes is a special-case feedstock repo which breaks this assumption

https://github.com/yuvipanda/pangeo-forge-runner/blob/677ad109348e50d4aa67f1009b5f184ab43beade/pangeo_forge_runner/feedstock.py#L18

For recipes in staged-recipes, meta.yaml and the recipe module are organized as described in item 3 of the list here: https://pangeo-forge.readthedocs.io/en/latest/pangeo_forge_cloud/recipe_contribution.html#making-a-pr

I'm not sure the best way to support this special case, but we definitely do want to support running recipes from staged-recipes PRs, so that we can run tests of these recipes before merging the PRs.

**Comment by yuvipanda** [comment]
Ah, I can add a 'subdir' field and have it default to 'feedstock' - and it can be passed anything else. That should support the staged-recipes case while still being generic enough

**Comment by cisaacstern** [comment]
Awesome yes I think this will do the trick 💫

**Comment by yuvipanda** [comment]
@cisaacstern you should be able to pass --feedstock-subdir as a commandline param now!

**Comment by cisaacstern** [comment]
Woohoo, thanks so much!
