### ISSUE TITLE
How to know when a bake is complete

### ISSUE THREAD

**Issue by cisaacstern** [yuvipanda/pangeo-forge-runner#16]
@sharkinsspatial previous lead the effort to create https://github.com/pangeo-forge/dataflow-status-monitoring, which once deployed sends a webhook to a pre-configured url as a notification of dataflow job completion. (And I should add, it works great!)

As I've been working on https://github.com/pangeo-forge/pangeo-forge-orchestrator/pull/80, I realize a limitation of this approach (at least as it's currently implemented), which is that the webhook url is hardcoded. In developing the GitHub App, a key requirement is the need to be very flexible regarding deployment url, because the deployment scenario is a moving target (could be proxying to localhost, could be an ephemeral review app, etc.), so the hardcoded url will not work.

I've chosen to open this issue here, rather than on https://github.com/pangeo-forge/dataflow-status-monitoring, in hopes that we can have a broader conversation about the best way to do this, without the assumption that any particular infrastructure (such as in https://github.com/pangeo-forge/dataflow-status-monitoring) is necessarily required. Certainly, if there's a way to ascertain when a Dataflow job has completed _without_ standing up additional infrastructure to do so, that'd be great. 

If I remember correctly, @yuvipanda previously floated the idea of polling dataflow from within the FastAPI application. Perhaps we could leverage `pangeo-forge-runner` to do this somehow? Just putting up this issue while I think of it, as a place to continue the discussion.

cc @rabernat @andersy005

**Comment by cisaacstern** [comment]
Just one other thought for now. In the interest of getting _something_ up and running ASAP, perhaps we can leverage the existing solution, and determine what url to post the webhook too dynamically from the resource labels (or similar) contained in the pubsub message, as is currently done for the job name [here](https://github.com/pangeo-forge/dataflow-status-monitoring/blob/32dd98f20e7e76f8b03a15f3d2b199b0762b5b44/src/main.py#L10-L11):

```python
    message = json.loads(pubsub_message)
    job_name = message["resource"]["labels"]["job_name"]
```

As a (interim, at least) solution, I think this will be tractable. I'll look into this more closely later this weekend.

**Comment by yuvipanda** [comment]
Yes, I'd love to add a command here that can take the job name, talk to dataflow and tell you 'oh yeah, it is done'. But might be more useful here to think about how to track notion of 'progress', and see if we can have more states than just 'done' 'not done'

**Comment by cisaacstern** [comment]
Thanks everyone for the feedback! I'm going to stick with `dataflow-status-monitoring` for now. Closing because I have a workable solution.
